<?php

namespace PublicationBundle\Repository;

/**
 * ArticleChercheurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleChercheurRepository extends \Doctrine\ORM\EntityRepository
{
}
